# Generated by Django 3.2.8 on 2021-10-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20211021_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='weight',
            field=models.CharField(choices=[('Super', 'Super'), ('Regular', 'Regular')], default='Regular', max_length=100),
        ),
    ]
