# Generated by Django 3.2.8 on 2021-10-21 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_category_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='weight',
            new_name='type',
        ),
    ]
