# Generated by Django 3.2.8 on 2021-10-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_weight_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='type',
            field=models.CharField(choices=[('Sale', 'Sale'), ('Purchase', 'Purchase')], default='Sale', max_length=100),
        ),
    ]
