# Generated by Django 3.2.8 on 2021-10-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20211025_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='for_him',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='seller',
            name='on_him',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
