# Generated by Django 3.2.8 on 2021-10-25 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_product_weight_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='old_account',
        ),
    ]
