# Generated by Django 3.2.8 on 2021-10-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_remove_seller_old_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight_value',
            field=models.FloatField(default=0),
        ),
    ]
