# Generated by Django 3.2.8 on 2021-10-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_product_weight_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicepayment',
            name='operation',
            field=models.CharField(choices=[('Add', 'Add'), ('Take', 'Take')], default='Add', max_length=5),
        ),
    ]
