# Generated by Django 3.2.8 on 2021-10-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_invoicepayment_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyboxoperation',
            name='operation',
            field=models.CharField(choices=[('Give', 'Give'), ('Take', 'Take')], default='Give', max_length=5),
        ),
        migrations.AlterField(
            model_name='invoicepayment',
            name='operation',
            field=models.CharField(choices=[('Give', 'Give'), ('Take', 'Take')], default='Give', max_length=5),
        ),
    ]
