# Generated by Django 3.2.8 on 2021-10-28 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20211025_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='for_him',
            new_name='old_account',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='on_him',
        ),
    ]
