# Generated by Django 3.2.8 on 2021-10-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_invoicepayment_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='currency',
        ),
        migrations.AddField(
            model_name='invoice',
            name='rate',
            field=models.FloatField(default=1),
        ),
    ]
