# Generated by Django 3.2.8 on 2021-10-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_auto_20211028_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='image',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoicepayment',
            name='image',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
