# Generated by Django 3.2.8 on 2021-10-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_invoice_discount_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
