# Generated by Django 3.2.8 on 2021-11-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_invoice_returned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='returned',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='type',
            field=models.CharField(choices=[('Sale', 'Sale'), ('Purchase', 'Purchase'), ('Return', 'Return')], default='Sale', max_length=100),
        ),
    ]
