# Generated by Django 3.2.8 on 2021-11-02 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_auto_20211102_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='remaining',
        ),
    ]
