# Generated by Django 3.2.8 on 2021-11-02 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_remove_invoice_remaining'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='expected_earn',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='payed',
        ),
    ]
