# Generated by Django 3.2.8 on 2021-11-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_auto_20211102_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='rate',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='discount',
            field=models.FloatField(default=0),
        ),
    ]
