# Generated by Django 3.2.8 on 2021-11-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_alter_invoice_earn'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceproduct',
            name='total_pices',
            field=models.FloatField(default=0),
        ),
    ]
