# Generated by Django 3.2.8 on 2021-11-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_invoiceproduct_total_pices'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceproduct',
            name='total_pices_count',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='Abbrivation',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
