# Generated by Django 3.2.8 on 2021-11-08 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_auto_20211108_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Abbrivation',
        ),
    ]
