# Generated by Django 3.2.9 on 2022-01-08 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_remove_product_abbrivation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.seller')),
            ],
        ),
    ]
