# Generated by Django 3.2.9 on 2022-04-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_sellerdiscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='old_type',
            field=models.CharField(choices=[('Sale', 'Sale'), ('Purchase', 'Purchase')], default='Sale', max_length=100),
        ),
    ]
